Name:           ros-indigo-jsk-baxter-startup
Version:        0.0.7
Release:        0%{?dist}
Summary:        ROS jsk_baxter_startup package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-baxter-core-msgs
Requires:       ros-indigo-baxter-description
Requires:       ros-indigo-baxter-examples
Requires:       ros-indigo-baxter-interface
Requires:       ros-indigo-baxter-tools
Requires:       ros-indigo-checkerboard-detector
Requires:       ros-indigo-dynamic-tf-publisher
Requires:       ros-indigo-image-view
Requires:       ros-indigo-joy
Requires:       ros-indigo-openni-launch
Requires:       ros-indigo-roseus
Requires:       ros-indigo-rostwitter
Requires:       ros-indigo-sound-play
Requires:       ros-indigo-topic-tools
BuildRequires:  ros-indigo-baxter-core-msgs
BuildRequires:  ros-indigo-baxter-description
BuildRequires:  ros-indigo-baxter-examples
BuildRequires:  ros-indigo-baxter-interface
BuildRequires:  ros-indigo-baxter-tools
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-checkerboard-detector
BuildRequires:  ros-indigo-dynamic-tf-publisher
BuildRequires:  ros-indigo-image-view
BuildRequires:  ros-indigo-joy
BuildRequires:  ros-indigo-openni-launch
BuildRequires:  ros-indigo-roseus
BuildRequires:  ros-indigo-rostwitter
BuildRequires:  ros-indigo-sound-play
BuildRequires:  ros-indigo-topic-tools

%description
The jsk_baxter_startup package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Jun 19 2015 Yuto Inagaki <inagaki@jsk.imi.i.u-tokyo.ac.jp> - 0.0.7-0
- Autogenerated by Bloom

* Fri Apr 10 2015 Yuto Inagaki <inagaki@jsk.imi.i.u-tokyo.ac.jp> - 0.0.6-0
- Autogenerated by Bloom

* Wed Apr 08 2015 Yuto Inagaki <inagaki@jsk.imi.i.u-tokyo.ac.jp> - 0.0.5-0
- Autogenerated by Bloom

* Fri Jan 30 2015 Yuto Inagaki <inagaki@jsk.imi.i.u-tokyo.ac.jp> - 0.0.4-1
- Autogenerated by Bloom

* Fri Jan 30 2015 Yuto Inagaki <inagaki@jsk.imi.i.u-tokyo.ac.jp> - 0.0.4-0
- Autogenerated by Bloom

