Name:           ros-indigo-jsk-robot
Version:        1.1.0
Release:        1%{?dist}
Summary:        ROS jsk_robot package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-baxtereus
Requires:       ros-indigo-fetcheus
Requires:       ros-indigo-jsk-201504-miraikan
Requires:       ros-indigo-jsk-baxter-desktop
Requires:       ros-indigo-jsk-baxter-startup
Requires:       ros-indigo-jsk-baxter-web
Requires:       ros-indigo-jsk-fetch-startup
Requires:       ros-indigo-jsk-nao-startup
Requires:       ros-indigo-jsk-pepper-startup
Requires:       ros-indigo-jsk-pr2-calibration
Requires:       ros-indigo-jsk-pr2-startup
Requires:       ros-indigo-jsk-robot-startup
Requires:       ros-indigo-jsk-robot-utils
Requires:       ros-indigo-naoeus
Requires:       ros-indigo-naoqieus
Requires:       ros-indigo-peppereus
Requires:       ros-indigo-pr2-base-trajectory-action
Requires:       ros-indigo-roseus-remote
BuildRequires:  ros-indigo-catkin

%description
Metapackage that contains robot packages for jsk-ros-pkg

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jul 16 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.1.0-1
- Autogenerated by Bloom

* Sun Jul 16 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.1.0-0
- Autogenerated by Bloom

* Fri Jun 17 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.6-2
- Autogenerated by Bloom

* Fri Jun 17 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.6-1
- Autogenerated by Bloom

* Fri Jun 17 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.6-0
- Autogenerated by Bloom

* Wed Apr 20 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.5-1
- Autogenerated by Bloom

