Name:           ros-indigo-jsk-fetch-startup
Version:        1.1.0
Release:        1%{?dist}
Summary:        ROS jsk_fetch_startup package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/jsk_fetch_startup
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-amcl
Requires:       ros-indigo-fetch-driver-msgs
Requires:       ros-indigo-fetch-moveit-config
Requires:       ros-indigo-fetch-navigation
Requires:       ros-indigo-fetch-teleop
Requires:       ros-indigo-joy
Requires:       ros-indigo-jsk-maps
Requires:       ros-indigo-jsk-robot-startup
Requires:       ros-indigo-map-server
Requires:       ros-indigo-move-base
Requires:       ros-indigo-rviz
Requires:       ros-indigo-safe-teleop-base
Requires:       ros-indigo-tf2-ros
Requires:       ros-indigo-topic-tools
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-rostest

%description
jsk_fetch_startup data/boost_sound.wav is downloaded from
https://www.youtube.com/watch?v=HM-xG0qXaeA

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jul 16 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.1.0-1
- Autogenerated by Bloom

* Sun Jul 16 2017 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.1.0-0
- Autogenerated by Bloom

* Fri Jun 17 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.6-2
- Autogenerated by Bloom

* Fri Jun 17 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.6-1
- Autogenerated by Bloom

* Fri Jun 17 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.6-0
- Autogenerated by Bloom

* Wed Apr 20 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.5-1
- Autogenerated by Bloom

* Mon Mar 21 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.4-0
- Autogenerated by Bloom

* Sat Mar 05 2016 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp> - 1.0.3-0
- Autogenerated by Bloom

