footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 1.0

local_costmap:
  transform_tolerance: 0.2
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_layer:
    inflation_radius: 0.2
  inflation_radius: 0.2
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true

  width: 10.0
  height: 10.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0

  publish_voxel_map: false
  map_type: voxel
  obstacle_layer:
    origin_z: 0.0
    z_voxels: 16
    z_resolution: 0.081
    unknown_cost_value: 0
    unknown_threshold: 8
    mark_threshold: 0
  origin_z: 0.0
  z_voxels: 16
  z_resolution: 0.081
  unknown_cost_value: 0
  unknown_threshold: 8
  mark_threshold: 0

  observation_sources: base_scan head_camera

  base_scan:
    sensor_frame: laser_link
    topic: /base_scan
    data_type: LaserScan
    expected_update_rate: 0.1
    observation_persistence: 0.0
    marking: true
    clearing: true
    min_obstacle_height: 0.25
    max_obstacle_height: 0.31
  head_camera:
    sensor_frame: head_camera_rgb_optical_frame
    topic: /head_camera/depth_registered/points
    data_type: PointCloud2
    expected_update_rate: 0.1
    observation_persistence: 0.0
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
